services:
  db:
    image: postgres:15
    container_name: supabase-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: your_secure_password
      POSTGRES_DB: portfolio_contacts
    volumes:
      - supabase-db-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  supabase-db-data:
  pgadmin-data:
